# Generated by Django 5.0 on 2023-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('dna', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='simulation.glip')),
            ],
        ),
    ]
