# Generated by Django 5.0 on 2023-12-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glip',
            name='action',
            field=models.CharField(default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='glip',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='glip',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
