# Generated by Django 5.0 on 2023-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_glip_action_glip_alive_alter_glip_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='setup', max_length=20)),
                ('tick', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
            ],
        ),
    ]
