# Generated by Django 5.0 on 2023-12-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='phase',
            field=models.IntegerField(default=0),
        ),
    ]
