# Generated by Django 5.0 on 2023-12-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_glip_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='glip',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
