# Generated by Django 5.0 on 2024-01-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_glip_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='births',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='run_time',
            field=models.IntegerField(default=0),
        ),
    ]
