# Generated by Django 5.0 on 2024-01-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0007_simulation_births_simulation_deaths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('births', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('run_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='births',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='population',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='run_time',
        ),
    ]
