# Generated by Django 5.0 on 2024-01-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0012_statistics_age_modifier_avg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='age_modifier_median',
        ),
    ]
