# Generated by Django 5.0 on 2024-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0013_remove_statistics_age_modifier_median'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='action_dating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='action_idle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='action_mating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='glip',
            name='dna',
            field=models.CharField(max_length=300),
        ),
    ]
