# Generated by Django 5.0 on 2024-01-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0014_statistics_action_dating_statistics_action_idle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='tolerance_age_both',
            new_name='tolerance_age_older',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='tolerance_age_high',
            new_name='tolerance_age_similiar',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='tolerance_age_low',
            new_name='tolerance_age_younger',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='tolerance_age_med',
        ),
    ]
