# Generated by Django 5.0 on 2024-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0016_household_glip_health_alter_glip_dna_glip_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glip',
            name='household',
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(related_name='household', to='simulation.glip'),
        ),
    ]
