# Generated by Django 5.0 on 2024-01-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0017_remove_glip_household_household_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household', to='simulation.glip'),
        ),
    ]
