# Generated by Django 5.0 on 2024-01-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0018_remove_household_members_household_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
        migrations.AddField(
            model_name='glip',
            name='household',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.household'),
        ),
    ]
