# Generated by Django 5.0 on 2024-01-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0019_remove_household_members_glip_household'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='age_modifier_avg',
            new_name='average_health',
        ),
        migrations.AlterField(
            model_name='glip',
            name='dna',
            field=models.CharField(max_length=40),
        ),
    ]
