# Generated by Django 5.0 on 2024-01-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0020_rename_age_modifier_avg_statistics_average_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glip',
            name='death_tick',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
