# Generated by Django 5.0 on 2024-01-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0021_glip_death_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='average_death_age',
            field=models.FloatField(default=0),
        ),
    ]
